; PlatformIO Project Configuration File for Waveshare ESP32-S3 Touch LCD 2.8"
; Dedicated Radio Firmware — High-Performance LVGL + I2S Web Radio
[platformio]
src_dir = .

[env:esp32s3_waveshare28]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = default_16MB.csv

; Enable 8MB Octal PSRAM & 16MB Flash
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DLV_CONF_INCLUDE_SIMPLE
    -I.
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    lvgl/lvgl@^8.3.11
    https://github.com/schreibfaul1/ESP32-audioI2S.git
