[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino

; Serial Monitor Options
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize

; Upload Options
upload_speed = 921600

; Memory & Partition Scheme: no_ota partition provides maximum flash space (~2MB) for BT stack
board_build.partitions = no_ota.csv

; Build Flags & Compiler Options
build_flags = 
    -DCORE_DEBUG_LEVEL=3               ; Info debug messages in Serial

extra_scripts = pre:fix_cmd.py

; Library Dependencies (Strict Git repository URL)
lib_deps = 
    https://github.com/pschatzmann/ESP32-A2DP.git
