[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino

; Serial Monitor Options
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize

; Upload Options
upload_speed = 921600

; Memory & Partition Scheme: standard huge app with OTA disabled to allow big audio buffers
board_build.partitions = huge_app.csv

; Build Flags & Compiler Options
build_flags = 
    -DCORE_DEBUG_LEVEL=3               ; Info debug messages in Serial
    -DARDUINO_RUNNING_CORE=1           ; Run Arduino loop on Core 1
    -DARDUINO_EVENT_RUNNING_CORE=1     ; Run Wi-Fi events on Core 1

extra_scripts = pre:fix_cmd.py

; Library Dependencies (Strict Git repository URL)
lib_deps = 
    https://github.com/schreibfaul1/ESP32-audioI2S.git
