#ifndef DINO_SPRITES_H
#define DINO_SPRITES_H

#include <stdint.h>
#include <lvgl.h>

// Color Definitions (Monochrome Chrome Palette in RGB565)
#define D_TRANS 0x0000 // Transparent
#define D_DARK  0x2945 // Classic Chrome Dino Slate Grey (#535353)
#define D_BLACK 0x0001 // Deep Black
#define D_WHITE 0xFFFF // Eye / Highlight White

#define DINO_W 22
#define DINO_H 24

// -----------------------------------------------------------------------------
// 1. T-Rex Running Frame 1 (Left Leg: 22x24 RGB565)
// -----------------------------------------------------------------------------
static const uint16_t dino_run1_map[DINO_W * DINO_H] = {
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_WHITE, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS
};

// -----------------------------------------------------------------------------
// 2. T-Rex Running Frame 2 (Right Leg: 22x24 RGB565)
// -----------------------------------------------------------------------------
static const uint16_t dino_run2_map[DINO_W * DINO_H] = {
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_WHITE, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS
};

// -----------------------------------------------------------------------------
// 3. T-Rex Jumping Frame (22x24 RGB565)
// -----------------------------------------------------------------------------
static const uint16_t dino_jump_map[DINO_W * DINO_H] = {
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_WHITE, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS
};

// -----------------------------------------------------------------------------
// 4. Classic Chrome Cactus (14x24 RGB565)
// -----------------------------------------------------------------------------
#define CACTUS_W 14
#define CACTUS_H 24
static const uint16_t cactus_map[CACTUS_W * CACTUS_H] = {
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS
};

// -----------------------------------------------------------------------------
// 5. Classic Floating Cloud (24x10 RGB565)
// -----------------------------------------------------------------------------
#define CLOUD_W 24
#define CLOUD_H 10
static const uint16_t cloud_map[CLOUD_W * CLOUD_H] = {
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS,
    D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,
    D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS,
    D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS,
    D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_DARK,  D_TRANS, D_TRANS, D_TRANS, D_TRANS, D_TRANS
};

// -----------------------------------------------------------------------------
// Image Descriptors (with Chroma Key transparency)
// -----------------------------------------------------------------------------
static const lv_img_dsc_t img_dino_run1 = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = DINO_W,
        .h = DINO_H,
    },
    .data_size = DINO_W * DINO_H * 2,
    .data = (const uint8_t*)dino_run1_map,
};

static const lv_img_dsc_t img_dino_run2 = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = DINO_W,
        .h = DINO_H,
    },
    .data_size = DINO_W * DINO_H * 2,
    .data = (const uint8_t*)dino_run2_map,
};

static const lv_img_dsc_t img_dino_jump = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = DINO_W,
        .h = DINO_H,
    },
    .data_size = DINO_W * DINO_H * 2,
    .data = (const uint8_t*)dino_jump_map,
};

static const lv_img_dsc_t img_cactus = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = CACTUS_W,
        .h = CACTUS_H,
    },
    .data_size = CACTUS_W * CACTUS_H * 2,
    .data = (const uint8_t*)cactus_map,
};

static const lv_img_dsc_t img_cloud = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = CLOUD_W,
        .h = CLOUD_H,
    },
    .data_size = CLOUD_W * CLOUD_H * 2,
    .data = (const uint8_t*)cloud_map,
};

#endif
