#ifndef MARIO_SPRITES_H
#define MARIO_SPRITES_H

#include <stdint.h>
#include <lvgl.h>

// Color Definitions (RGB565)
#define C_TRANS 0x0000 // Transparent (Chroma Keyed or Black)
#define C_RED   0xF900 // Mario Cap & Shirt Red
#define C_BLUE  0x021F // Overalls Blue
#define C_SKIN  0xFDE4 // Face & Skin Tone
#define C_BROWN 0x8200 // Hair & Shoes Brown
#define C_GOLD  0xFFE0 // Coin & Button Gold
#define C_GREEN 0x07E0 // Warp Pipe Green
#define C_DGRN  0x03E0 // Dark Green Pipe Outline
#define C_WHITE 0xFFFF // White Eyes & Highlights
#define C_BLACK 0x0001 // Black Outline

#define SPRITE_W 16
#define SPRITE_H 20

// -----------------------------------------------------------------------------
// 1. Classic Mario Standing / Running Frame 1 (16x20 RGB565)
// -----------------------------------------------------------------------------
static const uint16_t mario_stand_map[SPRITE_W * SPRITE_H] = {
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_SKIN,  C_SKIN,  C_BROWN, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_SKIN,  C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_SKIN,  C_BROWN, C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_RED,   C_RED,   C_BLUE,  C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_RED,   C_RED,   C_RED,   C_BLUE,  C_RED,   C_RED,   C_BLUE,  C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_RED,   C_RED,   C_RED,   C_RED,   C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_RED,   C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_SKIN,  C_RED,   C_BLUE,  C_GOLD,  C_BLUE,  C_BLUE,  C_GOLD,  C_BLUE,  C_RED,   C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_SKIN,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_BLUE,  C_BLUE,  C_BLUE,  C_TRANS, C_TRANS, C_BLUE,  C_BLUE,  C_BLUE,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS
};

// -----------------------------------------------------------------------------
// 2. Classic Mario Jumping Frame (16x20 RGB565)
// -----------------------------------------------------------------------------
static const uint16_t mario_jump_map[SPRITE_W * SPRITE_H] = {
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_SKIN,  C_SKIN,  C_BROWN, C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_SKIN,  C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_SKIN,  C_BROWN, C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_RED,   C_RED,   C_RED,   C_BLUE,  C_RED,   C_RED,   C_RED,   C_RED,   C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_RED,   C_RED,   C_RED,   C_BLUE,  C_BLUE,  C_BLUE,  C_RED,   C_RED,   C_RED,   C_RED,   C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_SKIN,  C_SKIN,  C_RED,   C_BLUE,  C_GOLD,  C_BLUE,  C_BLUE,  C_GOLD,  C_BLUE,  C_RED,   C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_SKIN,  C_SKIN,  C_SKIN,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_BLUE,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BLUE,  C_BLUE,  C_BLUE,  C_TRANS, C_TRANS, C_BLUE,  C_BLUE,  C_BLUE,  C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS
};

// -----------------------------------------------------------------------------
// 3. Classic Goomba Enemy (16x16 RGB565)
// -----------------------------------------------------------------------------
static const uint16_t goomba_map[16 * 16] = {
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS,
    C_TRANS, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS,
    C_BROWN, C_BROWN, C_BROWN, C_BLACK, C_WHITE, C_BLACK, C_BROWN, C_BROWN, C_BLACK, C_WHITE, C_BLACK, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS,
    C_BROWN, C_BROWN, C_BROWN, C_BLACK, C_WHITE, C_BLACK, C_BROWN, C_BROWN, C_BLACK, C_WHITE, C_BLACK, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS,
    C_BROWN, C_BROWN, C_BROWN, C_WHITE, C_WHITE, C_WHITE, C_BLACK, C_BLACK, C_WHITE, C_WHITE, C_WHITE, C_BROWN, C_BROWN, C_BROWN, C_TRANS, C_TRANS,
    C_TRANS, C_BROWN, C_BROWN, C_WHITE, C_WHITE, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_WHITE, C_WHITE, C_BROWN, C_BROWN, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_SKIN,  C_TRANS, C_TRANS, C_TRANS,
    C_TRANS, C_BLACK, C_BLACK, C_BLACK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BLACK, C_BLACK, C_BLACK, C_TRANS, C_TRANS, C_TRANS,
    C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_TRANS, C_TRANS,
    C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_TRANS, C_TRANS, C_TRANS, C_TRANS, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_BLACK, C_TRANS, C_TRANS
};

// -----------------------------------------------------------------------------
// LVGL Image Descriptors (with Chroma Key transparency)
// -----------------------------------------------------------------------------
static const lv_img_dsc_t img_mario_stand = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = SPRITE_W,
        .h = SPRITE_H,
    },
    .data_size = SPRITE_W * SPRITE_H * 2,
    .data = (const uint8_t*)mario_stand_map,
};

static const lv_img_dsc_t img_mario_jump = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = SPRITE_W,
        .h = SPRITE_H,
    },
    .data_size = SPRITE_W * SPRITE_H * 2,
    .data = (const uint8_t*)mario_jump_map,
};

static const lv_img_dsc_t img_goomba = {
    .header = {
        .cf = LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED,
        .always_zero = 0,
        .reserved = 0,
        .w = 16,
        .h = 16,
    },
    .data_size = 16 * 16 * 2,
    .data = (const uint8_t*)goomba_map,
};

#endif
